package com.kkhill.core.thing;

import com.kkhill.core.Catcher;
import com.kkhill.core.exception.IllegalThingException;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public abstract class Thing {

    /** id is unique, generated by core **/
    private String id;

    /** different things can share a friendly name **/
    private String friendlyName;

    private boolean available;
    private State state;
    private Map<String, Property> properties;
    private Map<String, Service> services;

    public Thing(String friendlyName, boolean available) {

        this.friendlyName = friendlyName;
        this.available = available;
        this.properties = new HashMap<>();
        this.services = new HashMap<>();
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    public String getFriendlyName() {
        return this.friendlyName;
    }

    public State getState() {
        return this.state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public boolean isAvailable() {
        return this.available;
    }

    public void disable() {
        this.available = false;
    }

    public void enable() {
        this.available = true;
    }

    public Map<String, Property> getProperties() {
        return this.properties;
    }

    public void addProperty(Property property) throws IllegalThingException {
        if(properties.containsKey(property.getName())) {
            throw new IllegalThingException(String.format(
                    "property: %s is duplicate", property.getName()));
        }
        this.properties.put(property.getName(), property);
    }

    public Property getProperty(String name) {
        return this.properties.get(name);
    }

    public Map<String, Service> getServices() {
        return this.services;
    }

    public void addService(Service service) throws IllegalThingException {
        if(services.containsKey(service.getName())) {
            throw new IllegalThingException(String.format(
                    "service: %s is duplicate", service.getName()));
        }
        this.services.put(service.getName(), service);
    }

    public Service getService(String name) {
        return this.services.get(name);
    }

    /**
     * @return parse annotations in a thing, and build it
     * @throws IllegalThingException
     */
    public String build() throws IllegalThingException {

        // TODO: generate unique Id, use friendlyName instead
        // Id is
//        String id = UUID.randomUUID().toString().replace("-", "");
        this.setId(this.friendlyName);

        // extract state and properties of thing
        Field[] fields = this.getClass().getDeclaredFields();
        int stateNum = 0;
        for(Field field : fields) {
            field.setAccessible(true);
            com.kkhill.core.annotation.State s = field.getAnnotation(com.kkhill.core.annotation.State.class);
            com.kkhill.core.annotation.Property p = field.getAnnotation(com.kkhill.core.annotation.Property.class);
            // build state
            if(s != null) {
                stateNum ++;
                if(stateNum > 1) throw new IllegalThingException("a thing must have only one state field");
                State state = new State(s.description(), this, field);
                this.setState(state);
            }
            // build properties
            if(p != null) {
                Property property = new Property(p.name(), p.description(), p.unitOfMeasurement(), this, field);
                this.addProperty(property);
            }
        }
        if(stateNum == 0) throw new IllegalThingException("a thing must have a state field");

        // extract services and polling method of a thing
        Method[] methods = this.getClass().getDeclaredMethods();
        for(Method method : methods) {
            method.setAccessible(true);
            com.kkhill.core.annotation.Service s = method.getAnnotation(com.kkhill.core.annotation.Service.class);
            // build service
            if(s != null) {
                Service service = new Service(s.name(), s.description(), this, method);
                if(s.poll()) {
                    service.enablePolling();
                    service.setInternal(service.getInternal());
                    // add to scheduler
                    Catcher.getScheduler().addPolledService(service);
                }
                this.addService(service);
            }
        }
        return id;
    }
}
